### PR TITLE
Update to SciJava Maven repository

### PR DESCRIPTION
**Pull request by ctrueden**

### CODE REVIEW

**Comment by ctrueden** [comment]
@ssgpers It would be good to merge this.

**Comment by ssgpers** [comment]
@ctrueden 

Sorry, took me some time to come back to it.

Now merged.

Every time something pushed to the master branch travis does the build. According to travis webpage, builds are successful, but I still can not find where they are deployed. At least not appearing on maven.scijava.org

**Comment by ctrueden** [comment]
It's not deploying anywhere. You can see this from the Travis log toward the top:

<blockquote>

== Configuring Maven ==
No deploy -- secure environment variables not available

</blockquote>

I added the encrypted variables so that Travis will be able to deploy to maven.scijava.org now.

**Comment by ctrueden** [comment]
It deployed: https://maven.scijava.org/#nexus-search;gav~de.embl.cba~java-utils-embl~~~

But _please_ do not use non-SNAPSHOT versions on the master branch. You will end up with multiple commits purporting to contain the same version of the project. Always use SNAPSHOTs, and use the `release-version.sh` script to cut releases. See [the docs](https://imagej.net/Development_Lifecycle#Phase_3:_Released) for details.

**Comment by ssgpers** [comment]
@ctrueden 

It works! Great! Thanks a lot!

**Pull request merged**
